### ISSUE TITLE
Network layer rewrite

### ISSUE THREAD

**Issue by youngjoon-lee** [logos-co/nomos-node#236]
To replace Waku with libp2p

_I'm putting what's in my head here before taking days off. So, please feel free to edit this._

- Create a `nomos-libp2p` crate that wraps rust-libp2p and provides some convenient APIs, which can be integrated as a network backend (`nomos-services/network/backends/libp2p.rs`).
  - Since rust-libp2p provides very raw/flexible interfaces, we may need to design the `nomos-libp2p` crate to hide boilerplates and provides simple interfaces with users.
  - https://github.com/logos-co/nomos-node/pull/237
- Create a `libp2p` network backend by using the `nomos-libp2p` crate. 
  - Started in https://github.com/logos-co/nomos-node/pull/237, but needs to be tested/completed in a different PR.
- Create a `libp2p` consensus adapter by using the `libp2p` network backend.
  - Here, we may need to have a data structure to query messages per 'view' (aka, message ordering). Where to implement the message ordering can be decided depending on which context we need for it. If we need Carnot-specific contexts for message ordering, it may be good to implement it in the `libp2p` consensus adapter. If not, it may be able to implemented in the `libp2p` network adapter or the `nomos-libp2p` crate. 
- Tests

After completing the first simple implementation, we may need to consider about further topics:
- libp2p transports (TCP, QUIC, or both)
- libp2p transport authentication (Noise)
- libp2p gossipsub message signing
- libp2p discovery protocols discV5? kademlia?

**Comment by youngjoon-lee** [comment]
The first iteration is done. The folowing bullet points need to be done in the future.

> - libp2p transports (TCP, QUIC, or both)
> - libp2p transport authentication (Noise)
> - libp2p gossipsub message signing

**Comment by Web3Knight** [comment]
Well noted, thanks
