### ISSUE TITLE
Integrate Mixnet with Waku network backend

### ISSUE THREAD

**Issue by youngjoon-lee** [logos-co/nomos-node#319]
In https://github.com/logos-co/nomos-node/pull/318, I’ve integrated mixnet only with libp2p backend. It should be also integrated with Waku backend.

**Comment by danielSanchezQ** [comment]
> In #318, I’ve integrated mixnet only with libp2p backend. It should be also integrated with Waku backend.

We do not need to support waku anymore for the time being. If we have everything ready in libp2p we can even ditch it.

**Comment by youngjoon-lee** [comment]
> We do not need to support waku anymore for the time being. If we have everything ready in libp2p we can even ditch it.

Good. I think our libp2p backend is 95% ready. 5% is optimization and unknown stuff :) Then, I'd say we can postpone this issue.
