### ISSUE TITLE
Mixnet: messages handle model

### ISSUE THREAD

**Issue by al8n** [logos-co/nomos-node#398]
Reference: https://github.com/logos-co/nomos-node/pull/386#discussion_r1324125862

- We need to use mpsc channel so that we only have one thread that handles message forwarding or sending (a fan-in model).
- When using this model, it means that some messages will be in the channel buffer. If a node crashes, then messages in the buffer will be lost. Do we care about this @youngjoon-lee @Zeegomo? If so, I think we need to introduce a write-ahead log, which will be used for recovering. When we have a message, first, write to this log, then send it to the buffer.

**Comment by danielSanchezQ** [comment]
> When using this model, it means that some messages will be in the channel buffer. If a node crashes, then messages in the buffer will be lost. Do we care about this @youngjoon-lee @Zeegomo? If so, I think we need to introduce a write-ahead log, which will be used for recovering. When we have a message, first, write to this log, then send it to the buffer.

I think in this case for mixnet node it do not matter if we lost the messages and node starts fresh new when restarted.
Other option is to use the `Overwatch` state to save it somewhere (local db for example), but I do not think we need to complicate things for now.

**Comment by Zeegomo** [comment]
Networking is best effort, our best effort at the moment probably stops at the node crashing 😄 
Btw, with the lock solution even if it's not in a buffer messages are still in volatile memory in the form of stack frames, so they would be lost anyway

**Comment by youngjoon-lee** [comment]
Sorry for my late comment. I agree with Daniel and Giacomo. I think we don't need WAL at this moment.

Actually, even if we call `tcp_stream.write(...)`, the data is buffered in the TCP buffer. That is, data could be lost if the node crashes before the TCP buffer is flushed.
