### ISSUE TITLE
Embed mixnode into nomos-node

### ISSUE THREAD

**Issue by youngjoon-lee** [logos-co/nomos-node#539]
https://www.notion.so/Mixnet-Specification-807b624444a54a4b88afa1cc80e100c2?pvs=4#d0f5c0ef93474179b49af149893226d3

> - We assume that **mix node is embeded into Nomos node**. In other words, both mix node and Nomos node are implemented as a single binary for ease of deployment.
>    - NOTE: We don’t need to worry about exposing an IP address of a node in order to maintain a mixnet topology, because IP address is not a critical factor if we design Privacy Proof of Stake sophisticatedly. Also, we aim to support home validators who don’t have multiple IP address in their place.

**Comment by danielSanchezQ** [comment]
@youngjoon-lee I think we can close this now right?

**Comment by youngjoon-lee** [comment]
Ah, yes. I'll close!
