### ISSUE TITLE
Verified Certificate state constraint when converting into VidCertificate

### ISSUE THREAD

**Issue by bacv** [logos-co/nomos-node#646]
At the moment Blob Certificate can be converted into the VidCertificate even if the verification is not successful.

We have required checks where needed (mempool), but this could further improved by introducing Certificate states and only allowing Into<VidCertificate> when the Certificate has Verified state.

More information in this comment: https://github.com/logos-co/nomos-node/pull/644#discussion_r1590675449

**Comment by danielSanchezQ** [comment]
Deprecated. Not using VID anymore
