### ISSUE TITLE
Integrate Indexer into verifier service tests after the Nomos DA Certificate is merged into `da-protocol-v1`

### ISSUE THREAD

**Issue by bacv** [logos-co/nomos-node#652]
https://github.com/logos-co/nomos-node/pull/650 tests the verifier service, but for complete e2e flow, `kzgrs-backend` needs to implement Certificate and related `nomos-core` traits.

Create a new PR for updating verifier integrations tests in `nomos-da-tests` to include creation of certificate after the attestations are received and pushing it the mempool service. Then use indexer service to receive data blobs for appid and index.

**Comment by danielSanchezQ** [comment]
Not using VID certificate anymore.
