### ISSUE TITLE
Blocking stream in tally, which caused the fn will never return.

### ISSUE THREAD

**Issue by al8n** [logos-co/nomos-node#97]
Hi @danielSanchezQ, I found that the implementation in the tally function will never return (the while loop), and will always keep waiting for the next. The situation can be easily reproduced by the latest `carnot-integration-test` branch's `mock.rs` test case.

```rust
async fn tally<S: Stream<Item = Self::Vote> + Unpin + Send>(
        &self,
        view: u64,
        mut vote_stream: S,
    ) -> Result<Self::Outcome, Self::TallyError> {
        let mut count_votes = 0;
        while let Some(vote) = vote_stream.next().await {
            if vote.view() != view {
                return Err(Error("Invalid vote".into()));
            }
            eprintln!("Vote received");
            count_votes += 1;
        }
        eprintln!("never enter here, because while loop never ends");
        if count_votes > self.threshold {
            Ok(MockQc { count_votes })
        } else {
            Err(Error("Not enough votes".into()))
        }
    }
```

**Comment by 3esmit** [comment]
Update for [rust-libp2p consumer PR #9](https://github.com/3esmit/rust-libp2p/pull/9), latest commit `3fabae7a`:

- Local direct WebRTC smoke: 10 consecutive runs pass after limiting native ICE gathering to the first local candidate.
- Hosted normal CI: all compile, test, MSRV, Clippy, formatting, semver, and example jobs pass. `cargo-deny` remains blocked by the inherited advisory set; no old Rustls/WebPKI advisory IDs appear.
- Hosted interoperability: Chromium transport tests pass. Native transport has the existing Java `ClosedChannelException` cases plus one `rust-v0.56` ↔ native WebRTC timeout; the other native WebRTC directions pass. Hole-punch remains blocked by relay negotiation/oneshot cancellation.
- No merge or downstream application claim yet; PR remains draft pending maintainer review.
